(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)




(* Method to relabel index of infinite sum such that there is no external power explicit *)
StandardizeSumPower::usage="Given a single sum, write exponent relative to a single power";

(*Method to put sum prefector inside sigma*)
StandardizeSumTerm::usage="Method to put sum prefector inside sigma";

(* Method to standardize all terms in multiple sum expression *)
StandardizeSumTerms::usage="Method to standardize all terms in multiple sum expression";

(* Given linear differential equation with known singular points, determine singular exponents *)
DeriveIndicialSolutions::usage="Given linear differential equation with known singular points, determine singular exponents."



(* Method to relabel index of infinite sum such that there is no external power explicit *)
Remove[StandardizeSumPower];
StandardizeSumPower[SumPart_,var_:v]:=Module[
	(* Internals *)
	{Ans,NewSumPart,OldPwr,OldDex,OldMinDex,OldMaxDex,NewDex,
	NewSumPart1,NewSumPart2,NewMinDex,NewMaxDex,OldDexRule},
	(* Extract Info from Sum *)
	{OldDex,OldMinDex,OldMaxDex} = SumPart[[2]];
	OldPwr = Exponent[SumPart[[1]],var];
	NewSumPart = SumPart;
	(* If needed, adjust labels and limits *)
	If[Simplify[OldPwr==OldDex],
		(* Do Nothing *)
		Ans = SumPart,
		(* Do Things *)
		OldDexRule = Solve[  NewDex == OldPwr, OldDex][[1]];
		NewSumPart1 = SumPart[[1]]/.OldDexRule;
		NewMinDex = OldMinDex+OldPwr-OldDex;
		NewMaxDex = OldMaxDex+OldPwr-OldDex; (* Only works for infinite sums anyway! *)
		NewSumPart2 = {NewDex,NewMinDex,NewMaxDex};
		NewSumPart[[1]] = NewSumPart1;
		NewSumPart[[2]] = NewSumPart2;
		Ans = NewSumPart/.{NewDex->OldDex};
	];
	Return[Ans];
]
(* Method to put sum prefector inside sigma *)
Remove[StandardizeSumTerm];
StandardizeSumTerm[Term_,var_:v]:=Module[ {Ans,SumPart,PreFact ,NewSumPart,NewPreFact,Limits,Pwr,OldDex,NewDex},
	SumPart = Term[[-1]]; PreFact = Term[[1;;-2]];
	NewSumPart = Simplify[SumPart[[1]] PreFact]; NewPreFact =  1;
	Ans = Term; Limits = SumPart[[2]];
	Ans[[-1]][[1]] = NewSumPart; Ans[[1;;-2]] = NewPreFact;
	Limits = Ans[[-1]][[2]];
	(* Standardize power label *)
	Ans = StandardizeSumPower[Ans,var];
	(*Print[Term,"  -->  ",Ans];*)
	Return[Ans]
]
(* Method to standardize all terms in multiple sum expression *)
Remove[StandardizeSumTerms];
StandardizeSumTerms[Terms_,var_:v]:=Module[ {Ans,ExpandedTerms},
	ExpandedTerms = Expand@Terms;
	Ans = ExpandedTerms;
	Table[ Ans[[INDEX]] = StandardizeSumTerm[ExpandedTerms[[INDEX]],var];, {INDEX,Length[ExpandedTerms]} ];
	Return[Ans];
]


Remove[DeriveIndicialSolutions];
DeriveIndicialSolutions[Dy_,y_,x_,SingularPoints_,order_:2,f_:f]:=Module[

	(* Internal variables *)
	{Ans,SingularScale,xSingular,SingularIndex,xRef,IndicialSolution,
	yTest,yDelta,TestDy,IndicialPolynomial,g,IndEqnK,SingularExponent},
	
	(*Determine a singular scaling for the solution ansatz*)
	SingularScale = 1; SingularIndex = {}; yDelta = 1;
	Do[
		(* Create expressions for singular indices *)
		SingularIndex = Join[SingularIndex,{ToExpression["k"<>ToString[k]]}];
		(* Construct singular scaling based on singular points and indices *)
		xSingular = SingularPoints[[k]];
		SingularScale = (x-xSingular)^SingularIndex[[k]] SingularScale;
		yDelta = (x-xSingular) yDelta;
		, 
		{k,Length[SingularPoints]}
	];
	
	(* Write series solution ansatz *)
	xRef = SingularPoints[[1]];
	g = Sum[a[k](x-xRef )^k,{k,0,order}];
	yTest = SingularScale g;
	
	(* Apply ansatz, and then determine indicial polynomial *)
	TestDy = Dy/.Table[D[y[x],{x,k}]->D[yTest,{x,k}],{k,0,order}];
	
	(* The Indicial Polynomial is determine by enforcing that the 
	solution is regular at the singular points. This is equivalent 
	to enforcing that the leading coefficient of the solution's series
	expansion is zero at the singular points. This latter condition 
	yields the indicial equation(s). *)
	IndicialPolynomial = Simplify[(yDelta/SingularScale)Coefficient[TestDy,a[0]]];
	
	(* Solve indicial equation at evenery singular point *)
	SingularExponent = {};
	Do[
		xSingular = SingularPoints[[k]];
		IndEqnK = (IndicialPolynomial/.{x -> xSingular})==0;
		IndicialSolution = Solve[ IndEqnK, SingularIndex[[k]] ];
		SingularExponent = Join[SingularExponent,{IndicialSolution}];
		, 
		{k,Length[SingularPoints]}
	];
	
	(* Return answer: The singular exponents and the singular scale function and associated Delta quantity *)
	Clear[f];
	Ans = Join[{SingularExponent},{ SingularScale f[x] }];
	Return[Ans];
]


Remove[DeriveIndicialSolutions2];
DeriveIndicialSolutions2[Dy_,y_,x_,SingularPoints_]:=Module[
	
	(* Internal variables *)
	{Ans,SingularScale,xSingular,SingularIndex,f,xRef,IndicialSolution,
	yTest,yDelta,TestDy,IndicialPolynomial,IndEqnK,SingularExponent},
	
	(*Determine a singular scaling for the solution ansatz*)
	SingularScale = 1; SingularIndex = {}; yDelta = 1;
	Do[
		(* Create expressions for singular indices *)
		SingularIndex = Join[SingularIndex,{ToExpression["k"<>ToString[k]]}];
		(* Construct singular scaling based on singular points and indices *)
		xSingular = SingularPoints[[k]];
		SingularScale = (x-xSingular)^SingularIndex[[k]] SingularScale;
		yDelta = (x-xSingular) yDelta;
		, 
		{k,Length[SingularPoints]}
	];
	
	(* Return answer *)
	Return[Ans];
	
]



